#!/bin/sh
#
# load wpa_supplicant
#

# Debian ifupdown needs the /run/network lock directory

case "$1" in
  start)
	printf "Start wpa_supplicant: "
	wpa_supplicant -iwlan0 -c/etc/wpa_supplicant.conf -B -P /var/run/wpa_supplicant.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	kill -HUP `cat /var/run/wpa_supplicant.pid`
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

